#!/bin/bash

usage() {
	echo "usage: ${progname} [options]"
	echo "options:"
	echo "       -f <filename>: display diff of a particular file"
	echo "       -F <flist>: file containing list of files to be diff'd"
	exit 1
}

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "Must be ran inside a view"
	exit 1
fi

filename=
flist=
while getopts ":hf:F:" arg; do
	case $arg in
	f)	filename=${OPTARG}
		;;
	F)	flist=${OPTARG}
		;;
	*)	usage
		;;
	esac
done
if [ -n "${filename}" ]; then
	p4 diff -du ${filename} | less
elif [ -n "${flist}" ]; then
	if [ ! -f ${flist} ]; then
		echo "${progname}: missing ${flist}"
		exit 1
	fi
	files="`cat ${flist}`"
	for f in ${files}; do
		p4 diff -du ${f} | less
	done
else
	p4 diff -du | less
fi
exit 0

