#!/bin/bash

. /usr/local/p4-tools/libp4.sh

usage() {
	echo "usage: ${progname} [options]"
	echo "options:"
	echo "       -f <filename>: display diff of a particular file"
	echo "       -F <flist>: file containing list of files to be diff'd"
	echo "       -d <dir>: directory to be diff'd"
	echo "       -o <outfile>: output file where diff will be stored (default stdout)"
	exit 1
}

pdiffvw_all() {
	if [ -n "${outfile}" ]; then
		p4 diff -du > ${outfile}
	else
		p4 diff -du | less
	fi
}

pdiffvw_file() {
	local filename=$1

	if [ -n "${outfile}" ]; then
		p4 diff -du ${filename} >> ${outfile}
	else
		p4 diff -du ${filename} | less
	fi
}

pdiffvw_files() {
	local files="$1"

	for f in ${files}; do
		pdiffvw_file ${f}
	done
}

pdiffvw_flist() {
	local flist=$1

	if [ ! -f ${flist} ]; then
		echo "${progname}: missing ${flist}"
		exit 1
	fi
	files="`cat ${flist}`"
	pdiffvw_files "${files}"
}

pdiffvw_dir() {
	dir=$1
	files_dir="`p4 opened | awk '{print $1}' | awk -Fdepot '{print $2}' | awk -F'#' '{print $1}' | awk -F${branch}/ '{print $2}' | grep ${dir}`"
	pdiffvw_files "${files_dir}"

}

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "Must be ran inside a view"
	exit 1
fi

filename=
flist=
outfile=
dir=
while getopts ":hf:F:o:d:" arg; do
	case $arg in
	f)	filename=${OPTARG}
		;;
	F)	flist=${OPTARG}
		;;
	o)	outfile=${OPTARG}
		;;
	d)	dir=${OPTARG}
		;;
	*)	usage
		;;
	esac
done

branch=`get_branch`

if [ -n "${outfile}" ]; then
	out_dirname=`dirname ${outfile}`
	mkdir -p ${out_dirname}
	echo > ${outfile}
fi

if [ -n "${filename}" ]; then
	pdiffvw_file ${filename}
elif [ -n "${flist}" ]; then
	pdiffvw_flist ${flist}
elif [ -n "${dir}" ]; then
	pdiffvw_dir ${dir}
else
	pdiffvw_all
fi
exit 0

