#!/bin/bash

. /usr/local/p4-tools/libp4.sh

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "${progname}: not inside any perforce view"
	exit 1
fi

branch=`get_branch`
rev=`get_rev`

echo "Current working view directory:" ${P4CLIENT_DIR}
echo "Current working view:" ${P4CLIENT}
echo "Current working branch:" ${branch}
echo "Client revision:" ${rev}
