#!/bin/bash

. /usr/local/p4-tools/libp4.sh

usage() {
	echo "usage: ${progname} [options]"
	echo "options:"
	echo "    -c <cid>: changelist ID specifier"
	echo "    -d: describe a changelist"
	echo "    -r: create a ccollab review"
	echo "    -R <rid>: update review rid with a new changelist"
	echo "    -l: list all reviews launched by ${whoami}"
	echo "examples:"
	echo "    ${progname} -l -- list all changelists by ${whoami}"
	echo "    ${progname} -- create a new changelist"
	echo "    ${progname} -c <cid> -- update a changelist"
	echo "    ${progname} -r -- create a new changelist and start a new review"
	echo "    ${progname} -c <cid> -r -- update a changelist and start a review"
	echo "    ${progname} -c <cid> -r -R <rid> -- update a changelist and post to review"
	echo "    ${progname} -c <cid> -d -- describe a changelist"
	exit 1
}

if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "Must be ran inside a view"
	exit 1
fi

progname=`basename $0`
whoami=`whoami`
clid=
review=0
list=0
describe=0
rid=
while getopts ":hc:rldR:" arg; do
	case $arg in
	c)	clid=${OPTARG}
		;;
	d)	describe=1
		;;
	r)	review=1
		;;
	R)	rid=${OPTARG}
		;;
	l)	list=1
		;;
	*)	usage
	esac
done

if [ ${list} -eq 1 ]; then
	p4 changes -u ${whoami}
	exit 0
elif [ ${describe} -eq 1 ]; then
	if [ -z ${clid} ]; then
		echo "${progname}: missing changelist identifier"
		exit 1
	fi
	p4 describe -du ${clid}
	exit 0
else
	p4 change ${clid}
	sleep 2
fi

if [ -z "${clid}" ]; then
	clid=`p4 changes -u ${whoami} | grep pending | head -1 | awk '{print $2}'`
	echo "p4 changelist ID: ${clid}"
fi

if [ ${review} -eq 1 ]; then
	if [ -n "${clid}" ]; then
		if [ -n "${rid}" ]; then
			ccollab addchangelist ${rid} ${clid}
		else
			ccollab addchangelist new ${clid}
		fi
	fi
fi
