#!/bin/bash

. /usr/local/p4-tools/libp4.sh

usage() {
	echo "usage: ${progname} [options]"
	echo "options:"
	echo "       -d: detailed information about each file checked out"
	echo "       -u: display untracked files"
	echo "       -a: display all files (both tracked and untracked)"
	echo "       -c: display files in a specified changelist"
	echo "       -n: display files NOT in any changelist"
	exit 1
}

pstatvw_tracked() {
	flist="`p4 opened | awk '{print $1}' | awk -Fdepot '{print $2}' | awk -F'#' '{print $1}' | awk -F${branch}/ '{print $2}'`"
#	awk -F/ '{\
#		for (i = 4; i < NF - 1; i++) {\
#			printf("%s/", $i);\
#		}\
#		printf("%s\n",$NF);\
#	}'`
	if [ -z "${flist}" ]; then
		return
	fi
	echo "List of files checked out in ${P4CLIENT}:"
	echo
	echo "$flist"
}

pstatvw_tracked_detail() {
	p4 diff -ds
}

pstatvw_untracked() {
	ignore_list="pyc swp x4"
	echo "List of untracked files in ${P4CLIENT} (ignoring file ext ${ignore_list}):"
	echo
	find -type f ! -name '*~' -print0| xargs -0 p4 fstat 2>&1 | \
		awk -v ignore_list="${ignore_list}" 'BEGIN{ \
			split(ignore_list,ignore_elems," "); \
			regex = ""; \
			for (i = 1; i < length(ignore_elems); i++) { \
				regex = regex ignore_elems[i] "|"; \
			} \
			regex = regex ignore_elems[i]; \

		} \
		/no such file/ { \
			if (!match($1, regex)) { \
				print $1; \
			} \
		}' | sed -e 's|^./||g'
}

pstatvw_changelist() {
	local clid=$1

	pending_clid_list=`get_clid_list_pending ${whoami} ${P4CLIENT}`
	found=`echo $pending_clid_list | grep ${clid}`
	if [ -z "${found}" ]; then
		echo "${progname}: ${clid} not found in this view"
		exit 1
	fi
	echo "List of files modified in changelist ${clid} in ${P4CLIENT}:"
	echo 
	get_clid_flist ${clid} ${branch}
}

pstatvw_nochangelist() {
	new_flist=`get_flist_nochangelist ${whoami} ${P4CLIENT} ${branch}`
	if [ -z "${new_flist}" ]; then
		return
	fi
	echo "List of files NOT in any changelist in ${P4CLIENT}:"
	echo
	echo ${new_flist} | tr " " "\n"
}

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "${progname}: not inside any perforce view"
	exit 1
fi

whoami=`whoami`
detail=0
untracked=0
all=0
clid=
nocl=0
while getopts ":hduac:n" arg; do
	case $arg in
	d)	detail=1
		;;
	u)	untracked=1
		;;
	a)	all=1
		;;
	h)	usage
		;;
	c)	clid=${OPTARG}
		;;
	n)	nocl=1
		;;
	esac
done

branch=`get_branch`

if [ ${detail} -eq 1 ]; then
	pstatvw_tracked_detail
elif [ ${untracked} -eq 1 ]; then
	pstatvw_untracked
elif [ ${all} -eq 1 ]; then
	pstatvw_tracked
	echo
	pstatvw_untracked
elif [ -n "${clid}" ]; then
	pstatvw_changelist ${clid}
elif [ ${nocl} -eq 1 ]; then
	pstatvw_nochangelist
else
	pstatvw_tracked
fi
echo
