#!/bin/bash

usage() {
	echo "usage: ${progname} [-f <filename>]"
	echo "       -f: display log of a particular file"
	echo "       -u: display untracked files"
	exit 1
}

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "${progname}: not inside any perforce view"
	exit 1
fi

detail=0
untracked=0
while getopts ":hdu" arg; do
	case $arg in
	d)	detail=1
		;;
	u)	untracked=1
		;;
	h)	usage
		;;
	esac
done

if [ ${detail} -eq 1 ]; then
	p4 diff -ds
elif [ ${untracked} -eq 1 ]; then
	ignore_list="pyc swp x4"
	echo "List of untracked files in ${P4CLIENT} - ignoring file extensions ${ignore_list}"
	find -type f ! -name '*~' -print0| xargs -0 p4 fstat 2>&1 | \
		awk -v ignore_list="${ignore_list}" 'BEGIN{ \
			split(ignore_list,ignore_elems," "); \
			regex = ""; \
			for (i = 1; i < length(ignore_elems); i++) { \
				regex = regex ignore_elems[i] "|"; \
			} \
			regex = regex ignore_elems[i]; \

		} \
		/no such file/ { \
			if (!match($1, regex)) { \
				print $1; \
			} \
		}'
else
	flist="`p4 opened | awk '{print $1}' | awk -Fdepot '{print $2}' | awk -F'#' '{print $1}'`"
	echo "List of files checked out in ${P4CLIENT}:"
	echo "$flist"
fi
echo
