#!/bin/bash

. /usr/local/p4-tools/libp4.sh

usage() {
	echo "usage: ${progname} [options]"
	echo "options:"
	echo "       -d: detailed information about each file checked out"
	echo "       -u: display untracked files"
	echo "       -a: display all files (both tracked and untracked)"
	exit 1
}

pstatvw_tracked() {
	flist="`p4 opened | awk '{print $1}' | awk -Fdepot '{print $2}' | awk -F'#' '{print $1}' | awk -F${branch}/ '{print $2}'`"
#	awk -F/ '{\
#		for (i = 4; i < NF - 1; i++) {\
#			printf("%s/", $i);\
#		}\
#		printf("%s\n",$NF);\
#	}'`
	echo "List of files checked out in ${P4CLIENT}:"
	echo
	echo "$flist"
}

pstatvw_tracked_detail() {
	p4 diff -ds
}

pstatvw_untracked() {
	ignore_list="pyc swp x4"
	echo "List of untracked files in ${P4CLIENT} (ignoring file ext ${ignore_list}):"
	echo
	find -type f ! -name '*~' -print0| xargs -0 p4 fstat 2>&1 | \
		awk -v ignore_list="${ignore_list}" 'BEGIN{ \
			split(ignore_list,ignore_elems," "); \
			regex = ""; \
			for (i = 1; i < length(ignore_elems); i++) { \
				regex = regex ignore_elems[i] "|"; \
			} \
			regex = regex ignore_elems[i]; \

		} \
		/no such file/ { \
			if (!match($1, regex)) { \
				print $1; \
			} \
		}' | sed -e 's|^./||g'
}

progname=`basename $0`
if [ -z "${P4CLIENT}" -o -z "${P4CLIENT_DIR}" ]; then
	echo "${progname}: not inside any perforce view"
	exit 1
fi

detail=0
untracked=0
all=0
while getopts ":hdua" arg; do
	case $arg in
	d)	detail=1
		;;
	u)	untracked=1
		;;
	a)	all=1
		;;
	h)	usage
		;;
	esac
done

branch=`get_branch`

if [ ${detail} -eq 1 ]; then
	pstatvw_tracked_detail
elif [ ${untracked} -eq 1 ]; then
	pstatvw_untracked
elif [ ${all} -eq 1 ]; then
	pstatvw_tracked
	echo
	pstatvw_untracked
else
	pstatvw_tracked
fi
echo
