#!/bin/bash

usage() {
	echo "usage: ${progname} [screen-name]"
	exit 1
}

launch() {
	local screen_list="$1"

	typeset -a _array_entries
	typeset -i count=0
	echo "You have the following active screens available:"
	for s in ${screen_list}; do
		count=${count}+1
		_array_entries[${count}]=${s}
	done
	PS3="Select screen ID: "
	select s in "${_array_entries[@]}"
	do case ${REPLY} in
	([1-9]*)
		if (( ${REPLY} <= ${count} ))
		then
			screen_id=${_array_entries[${REPLY}]}
		else
			screen_id=`echo "${screen_list}" | awk -F. -v reply=${REPLY} 'reply==$1{ print $0 }'`
		fi
		if [ -n "${screen_id}" ]; then
			screen -r -D -R ${screen_id}
			break
		else
			echo "${progname}: invalid screen ID specified"
		fi
		;;
	c|C)	clear
		;;
	q|Q)	break
		;;
	esac
	REPLY=""
	done
}

progname=`basename $0`
target="$1"
hostname=`hostname | awk -F. '{print $1}'`
screen_list="`screen -list | grep ${hostname} | grep -v Socket |awk '{print $1}'`"
if [ "${target}" = "-h" ]; then
	usage
fi

if [ "${screen_list}" = "" ]; then
	echo "${progname}: no screen found in host ${hostname}"
	exit 1
fi

n_screen=`echo ${screen_list} | wc -w`
if [ ${n_screen} -eq 1 ]; then
	screen -r -R -D ${screen_list}
elif [ -n "${target}" ]; then
	match="`echo "${screen_list}" | grep "${target}"`"
	if [ -z "${match}" ]; then
		echo "${progname}: no active screens matches with name ${target}"
		exit 1
	fi
	n_screen=`echo ${match} | wc -w`
	if [ ${n_screen} -eq 1 ]; then
		screen -r -R -D ${match}
	else
		launch "${match}"
	fi
else
	launch "${screen_list}"
fi
