#!/bin/bash

usage() {
	echo "usage: ${progname} <profile_type> <port> <ipaddr> [bond_type]"
	exit 1
}
progname=`basename $0`
if [ $# -lt 3 ]; then
	usage
fi
profile=$1
if [ -z "${profile}" ]; then
	usage
fi
port=$2
if [ -z "${port}" ]; then
	usage
fi
ipaddr=$3
if [ -z "${ipaddr}" ]; then
	usage
fi
bond_type=$4
bond_arg=
if [ -n "${bond_type}" ]; then
	bond_arg="--bond-mode ${bond_type}"
fi
new_binary_path=/var/tmp
new_dp_path=${new_binary_path}/vrs-dpdk-datapath
new_tool_path=${new_binary_path}/vrs_dpdk_sys.py
new_rte_kni_path=${new_binary_path}/rte_kni.ko
new_igb_uio_path=${new_binary_path}/igb_uio.ko

echo "Starting Network manager ... "
service NetworkManager start
echo ""

echo "Stopping current binaries ..."
vrs-dpdkctl sys/deconfig '--dpdk --stop-datapath'

if [ -s ${new_dp_path} ]; then
	printf "Copying ${new_dp_path} to /usr/sbin ... "
	cp /var/tmp/vrs-dpdk-datapath /usr/sbin
	echo "done"
fi
if [ -s "${new_tool_path}" ]; then
	printf "Copying ${new_tool_path} to /usr/share ... "
	cp /var/tmp/*dpdk*py /usr/share/openvswitch/python/ovs/nuage
	echo "done"
fi
if [ -s "${new_rte_kni_path}" ]; then
	printf "Copying ${new_rte_kni_path} to /usr/share ... "
	cp ${new_rte_kni_path} /usr/share/openvswitch/dpdk/kmod
	echo "done"
fi
echo ""
if [ -s "${new_igb_uio_path}" ]; then
	printf "Copying ${new_igb_uio_path} to /usr/share ... "
	cp ${new_igb_uio_path} /usr/share/openvswitch/dpdk/kmod
	echo "done"
fi
echo ""

echo "Starting new datapath ..."
if [ -n "${profile}" ]; then
	vrs-dpdkctl sys/config "--dpdk --profile ${profile} --hw-crypto on" #--pdump --skip-plugins ipsec"
else
	vrs-dpdkctl sys/config '--dpdk --pages 1024 --ports 1 --start-datapath' #--hw-crypto on --skip-plugins ipsec'
fi
sleep 3
vrs-dpdkctl port/add "--dpdk --device ${port} ${bond_arg}"
echo ""

echo "Stopping Network manager ... "
sleep 5
service NetworkManager stop
echo ""

echo "Reprogramming ${ipaddr} to dpdk_bond0 ... "
sleep 1
ifconfig dpdk_bond0 ${ipaddr}/24
echo ""
