#!/bin/bash

usage() {
	echo "usage: ${progname} <profile> <port>[,<port>] <single|dual> <qat|aesni> [bond_type]"
	exit 1
}
progname=`basename $0`
if [ $# -lt 2 ]; then
	usage
fi
profile=$1
if [ -z "${profile}" ]; then
	usage
fi
port_list=$2
if [ -z "${port_list}" ]; then
	usage
fi
uplink_type=$3
n_ports=0
if [ -z "${uplink_type}" ]; then
	usage
elif [ "${uplink_type}" = "single" ]; then
	n_ports=1
elif [ "${uplink_type}" = "dual" ]; then
	n_ports=2
else
	echo "${progname}: uplink_type can be \'single\' or \'dual\'"
	usage
fi
encmode=$4
if [ -z "${encmode}" ]; then
	echo "${progname}: need encryption mode 'qat' or 'aesni'"
	usage
fi
encopt=
if [ "${encmode}" = "aesni" ]; then
	encopt="--hw-crypto off"
else
	encopt="--hw-crypto on"
fi
bond_type=$5
bond_arg=
if [ -n "${bond_type}" ]; then
	bond_arg="--bond-mode ${bond_type}"
fi
new_binary_path=/var/tmp
new_dp_path=${new_binary_path}/vrs-dpdk-datapath
new_tool_path=${new_binary_path}/vrs_dpdk_sys.py

echo "Stopping current binaries ..."
vrs-dpdkctl sys/deconfig '--dpdk --stop-datapath'
sed -i -e "s/^UPLINK1_PORT_MASTER_SLAVE=.*/#UPLINK1_PORT_MASTER_SLAVE=/g" /etc/default/openvswitch
sed -i -e "s/^UPLINK2_PORT_MASTER_SLAVE=.*/#UPLINK2_PORT_MASTER_SLAVE=/g" /etc/default/openvswitch

if [ -s ${new_dp_path} ]; then
	printf "Copying ${new_dp_path} to /usr/sbin ... "
	cp /var/tmp/vrs-dpdk-datapath /usr/sbin
	echo "done"
fi
if [ -s "${new_tool_path}" ]; then
	printf "Copying ${new_tool_path} to /usr/share ... "
	cp /var/tmp/*dpdk*py /usr/share/openvswitch/python/ovs/nuage
	echo "done"
fi
echo ""

echo "Starting new datapath ..."
if [ -n "${profile}" ]; then
	vrs-dpdkctl sys/config "--dpdk --ports ${n_ports} --profile ${profile} ${encopt}"
else
	vrs-dpdkctl sys/config "--dpdk --ports ${n_ports} --pages 1024 --start-datapath ${encopt}"
fi
port1=`echo ${port_list} | awk -F, '{print $1}'`
port1_iface=`echo ${port1} | awk -F. '{print $1}'`
port1_vid=`echo ${port1} | awk -F. '{print $2}'`
if [ -n "${port1_vid}" ]; then
	dpdk_bond0_iface=dpdk_bond0.${port1_vid}
else
	dpdk_bond0_iface=dpdk_bond0
fi
sleep 3
echo "modifying /etc/default/openvswitch for ${port1}"
sed -i -e "s/#UPLINK2_PORT_MASTER_SLAVE=/UPLINK2_PORT_MASTER_SLAVE=${port1}:${dpdk_bond0_iface}/g" /etc/default/openvswitch
sleep 1
vrs-dpdkctl port/add "--dpdk --device ${port1_iface} ${bond_arg}"
if [ ${n_ports} -eq 2 ]; then
	sleep 3
	port2=`echo ${port_list} | awk -F, '{print $2}'`
	port2_iface=`echo ${port2} | awk -F. '{print $1}'`
	port2_vid=`echo ${port2} | awk -F. '{print $2}'`
	if [ -z "${port2}" ]; then
		echo "${progname}: no value specified for second port"
	else
		if [ -n "${port2_vid}" ]; then
			dpdk_bond1_iface=dpdk_bond1.${port2_vid}
		else
			dpdk_bond1_iface=dpdk_bond1
		fi
		echo "modifying /etc/default/openvswitch for ${port2}"
		sed -i -e "s/#UPLINK1_PORT_MASTER_SLAVE=/UPLINK1_PORT_MASTER_SLAVE=${port2}:${dpdk_bond1_iface}/g" /etc/default/openvswitch
		sleep 1
		vrs-dpdkctl port/add "--dpdk --device ${port2_iface} ${bond_arg}"
	fi
fi
echo ""
