#!/usr/bin/python

import sys
import os

sys.path.append("/usr/local/aos/pylib/wlan")
import wlan_controller

def usage():
	print "usage: " + progname + " <device-ip-address>"
	exit(1)

def main(argc, argv):
	if argc < 2:
		usage()
	device = argv[0]
	c = wlan_controller.Device(device)
	c.telnet_session()

if __name__ == "__main__":
	argc = len(sys.argv)
	progfile = os.path.basename(sys.argv[0])
	progname = progfile.split(".")[0]
	main(argc, sys.argv[1:])

