#!/usr/bin/python

import sys
import os
import getopt

sys.path.append("/usr/local/aos/pylib/wlan")
import wlan_controller

sys.path.append("/usr/local/aos/pylib/system")
import shell

def usage():
	print "usage: " + progname + " <options> <device-ip-address>"
	print "options:"
	print "    -t: enable telnet at specified device"
	print "    -T: establish a telnet session with specified device"
	exit(1)

def main(argc, argv):
	try:
		opts, args = getopt.getopt(argv, "ht:T:");
	except getopt.GetoptError as err:
		print progname + ": invalid argument, " + str(err)
		usage()
	device = ""
	telnet = False
	enable_telnet = False
	for opt, arg in opts:
		if opt == "-t":
			device = arg
			enable_telnet = True
		elif opt == "-T":
			device = arg
			telnet = True

	if (device == ""):
		print progname + ": need a controller device to operate on"
		usage()

	if shell.is_alive(device) == False:
		print progname + ": controller " + device + " appears to be down"
		return
	c = wlan_controller.Device(device)

	if (telnet == True):
		c.telnet_session()
	elif (enable_telnet == True):
		c.enable_telnet()

if __name__ == "__main__":
	argc = len(sys.argv)
	progfile = os.path.basename(sys.argv[0])
	progname = progfile.split(".")[0]
	main(argc, sys.argv[1:])

