#!/usr/bin/python

import sys
import os
import getopt
import time

sys.path.append("/usr/local/aos/pylib/wlan")
import wlan_controller
import wlan_ap

sys.path.append("/usr/local/aos/pylib/system")
import shell
import net

def usage():
	print "usage: " + progname + " <type> <device> <options>"
	print "arguments:"
	print "    type: 'controller'"
	print "    device: IP address of the device"
	print "options:"
	print "    -s: status of a specified controller"
	print "    -t: enable telnet at specified device"
	print "    -T: establish a telnet session with specified device"
	print "    -c: generate a controller datapath coredump"
	print "    -r: reload the specified controller"
	print "    -C: generate and copy out coredump tarball from a device"
	exit(1)

def main(argc, argv):
	all_device_types = [
		{ 'type' : "controller", 'handler': manage_controller, }
	]
	if (argc < 3):
		usage()
	try:
		opts, args = getopt.getopt(argv[2:], "htTcsrC");
	except getopt.GetoptError as err:
		print progname + ": invalid argument, " + str(err)
		usage()
	type = argv[0]
	device = argv[1]
	found = False
	for d in all_device_types:
		if (d['type'] == type):
			found = True
			break
	if (found == False):
		print progname + ": invalid type specified"
		usage()
	telnet = False
	enable_telnet = False
	dp_core = False
	status = False
	reload = False
	copyout_core = False
	for opt, arg in opts:
		if opt == "-t":
			enable_telnet = True
		elif opt == "-T":
			telnet = True
		elif opt == "-c":
			dp_core = True
		elif opt == "-C":
			copyout_core = True
		elif opt == "-s":
			status = True
		elif opt == "-r":
			reload = True

	if (device == ""):
		print progname + ": need a controller device to operate on"
		usage()

	if net.is_alive(device) == False:
		print progname + ": controller " + device + " appears to be down"
		return
	options = {
		'telnet' : telnet,
		'enable_telnet': enable_telnet,
		'dp_core': dp_core,
		'status': status,
		'reload': reload,
		'copyout_core': copyout_core,
	}
	for d in all_device_types:
		if (d['type'] == type):
			d['handler'](device, options)
			return

def manage_controller(device, options):
	telnet = options['telnet']
	enable_telnet = options['enable_telnet']
	dp_core = options['dp_core']
	status = options['status']
	reload = options['reload']
	copyout_core = options['copyout_core']

	c = wlan_controller.Device(device)
	apList = wlan_ap.APList(c)

	if (telnet == True):
		c.telnet_session()
	elif (enable_telnet == True):
		c.enable_telnet()
	elif (dp_core == True):
		c.gen_dp_core()
		print "Waiting for " + device + " to reboot, please wait"
		while (True):
			sys.stdout.write(".")
			sys.stdout.flush()
			time.sleep(5)
			if (net.is_alive(device) == True):
				break
		print
		print "Controller " + device + " is now alive"
		if c.tar_crash() == True:
			time.sleep(5)
			dst_user = shell.whoami()
			dst_host_canon = "dev-" + dst_user
			dst_host = net.getent(dst_host_canon)
			c.scp_crash(dst_user, dst_host, "/var/tmp")
	elif (copyout_core == True):
		if c.tar_crash() == True:
			time.sleep(5)
			dst_user = shell.whoami()
			dst_host_canon = "dev-" + dst_user
			dst_host = net.getent(dst_host_canon)
			c.scp_crash(dst_user, dst_host, "/var/tmp")
		else:
			print "Coredump does not exist on " + device
	elif (status == True):
		platid = c.get_platid()
		boot_partition = c.get_boot_partition()
		uptime = c.get_uptime()
		switchrole = c.get_switchrole()
		naps = apList.get_naps()
		sw_vers, build_number, label, build_date = c.get_boot_image_version()
		print "Platform: %s" %platid
		print "Uptime: %s" %uptime
		print "Switch Role: %s" %switchrole
		print "Boot Information:"
		print "\tPartition: %s" %boot_partition
		print "\tSW Version (build): %s (%s)" % (sw_vers, build_number)
		print "\tLabel: %s" % (label)
		print "\tBuild Date: %s" % (build_date)
		print "Number of active APs: %d" %(naps)
		if (naps != 0):
			print "%-17s %-15s %-5s %-s" %("Name", "IP", "Type", "Group")
			for i in range(0, naps):
				ap = apList.info(i)
				print "%-17s %-15s %-5s %-s" %(ap.name, ap.ip, ap.type, ap.group)
	elif (reload == True):
		c.reload()
	else:
		print progname + ": Unsupported operation"
		usage()

if __name__ == "__main__":
	argc = len(sys.argv)
	progfile = os.path.basename(sys.argv[0])
	progname = progfile.split(".")[0]
	main(argc, sys.argv[1:])

