#!/bin/bash

usage() {
	echo "usage: ${progname} <view> <crashinfo-path> [options]"
	echo "options:"
	echo "       -p <path>: P4 view root directory (default /data/<login>/adu/views)"
	echo "       -t <path>: AOS tools path (default /usr/local/aos/tools)"
	exit 1
}

append_gdb_env() {
	cat >> ${gdbscript} << EOF
set logging redirect on
set logging file ${tech_support_log}
set logging on
set print repeat 0
set pagination off
EOF
}

append_source_dirs() {
	for i in ${gdbscripts}; do
		cat >> ${gdbscript} << EOF
print "${marker} source ${i}"
source -v ${gdbscripts_dir}/${i}
EOF
	done
}

append_basic_core_info() {
cat >> ${gdbscript} << EOF
print "${marker} info files"
info files
EOF
}

append_gdbcomm_runs() {
	n=${#gdbcomms[@]}
	i=0
	while [ $i -lt $n ]; do
		cat >> ${gdbscript} << EOF
print "${marker} ${gdbcomms[$i]}"
${gdbcomms[$i]}
EOF
		i=`expr $i + 1`
	done
}

append_gdbproc_runs() {
	for i in ${gdbprocs}; do
		cat >> ${gdbscript} << EOF
print "${marker} ${i}"
${i}
EOF
	done
}

append_quit() {
	cat >> ${gdbscript} << EOF
quit
EOF
}

create_gdbscript() {
	echo > ${gdbscript}
	append_gdb_env
	append_basic_core_info
	append_gdbcomm_runs
	append_source_dirs
	append_gdbproc_runs
	append_quit
}

run_gdb() {
	p4view_opt=
	if [ -n "${P4VIEW_ROOTDIR}" ]; then
		p4view_opt="-p ${P4VIEW_ROOTDIR}"
	fi
	tools_opt=
	if [ -n "${AOS_TOOLS_DIR}" ]; then
		tools_opt="-t ${AOS_TOOLS_DIR}"
	fi
	${sos_crash_debug} ${P4CLIENT} ${crashdump_path} -x ${gdbscript} -n ${tools_opt} ${p4view_opt}
}

cleanup_gdbscript() {
	rm -f ${gdbscript}
}

finalize_log() {
	sed -e 's/''\$''.*= "=======/"(gdb)/g' ${tech_support_log} | sed -e 's/"//g' > ${tech_support_log}.$$
	mv ${tech_support_log}.$$ ${tech_support_log}
	echo "Tech Support Log location: ${tech_support_log}"
}

gdbscripts="\
	bwm.gdb \
	python/bwm.py \
	xlp/cpu.gdb \
	xlp/python/cpu.py \
	xlp/dma.gdb \
	xlp/python/dma.py \
	xlp/sbeth.gdb \
	xlp/python/sbeth.py \
	xlp/stats.gdb \
	xlp/python/stats.py \
"

gdbprocs="\
	print_cpu_utilization \
	dump_all_stats \
	print_all_bwms \
	print_dma_info \
	sbeth_leak_stats \
	sbeth_print_freelist \
"

gdbcomms=(\
'info threads' \
'thread apply all backtrace' \
'thread apply all backtrace full' \
)

progname=`basename $0`
P4CLIENT=$1
crashdump_path=$2
timestamp=`date +"%Y%m%d%H%M%S"`
tech_support_log=/var/tmp/${progname}.${timestamp}.txt
gdbscript=/var/tmp/gdbscript.$$
marker="======="

if [ -z "${P4CLIENT}" ]; then
	echo "${progname}: missing view name"
	usage
fi

if [ -z "${crashdump_path}" ]; then
	echo "${progname}: missing crashdump path"
	usage
fi

shift;shift

while getopts ":p:t:" arg; do
	case ${arg} in
	p)
	P4VIEW_ROOTDIR=${OPTARG}
	;;
	t)
	AOS_TOOLS_DIR=${OPTARG}
	;;
	*)
	echo "${progname}: invalid option ${arg}"
	usage
	;;
	esac
done

user=`whoami`
P4VIEWDIR_DEF=/data/${user}/adu/views
P4CLIENT_DIR=${P4VIEW_ROOTDIR:-${P4VIEWDIR_DEF}}/${P4CLIENT}
gdbscripts_dir=${P4CLIENT_DIR}/sos/gdbscripts

AOS_TOOLS_DEF=/usr/local/aos/tools
AOS_TOOLS=${AOS_TOOLS_DIR:-${AOS_TOOLS_DEF}}
sos_crash_debug=${AOS_TOOLS}/sos-crash-debug

echo "Crashdump path: ${crashdump_path}"
echo "Tech Support Log location: ${tech_support_log}"
echo "AOS Tools: ${AOS_TOOLS}"
echo "P4 client path: ${P4CLIENT_DIR}" 

create_gdbscript
run_gdb
cleanup_gdbscript
finalize_log
