#!/bin/sh

usage() {
	echo "usage: ${progname} <udp|tcp> <dst-ip-addr> <mins> <mtu> [rate]"
	exit 1
}

progname=`basename $0`
proto=$1
dst_ip=$2
duration_mins=$3
mtu=$4
if [ -z "${mtu}" ]; then
	mtu=1450
	rate=$4
else
	rate=$5
fi
n_parallel_flows=50
interval_secs=5
report_interval_secs=60
if [ -z "$duration_mins" ]; then
	usage
fi
proto_opt=
mtu_opt="-l ${mtu}"
case ${proto} in
"udp")	proto_opt=-u
	;;
"tcp")	;;
esac
rate_opt=
parallel_opt=
i=0
iperf_out=/var/log/iperf.${dst_ip}.out
echo "iperf results file: ${iperf_out}"
if [ -n "${rate}" ]; then
	rate_opt="-b ${rate}" 
	parallel_opt=
	n_parallel_flows=0
else
	parallel_opt="-P ${n_parallel_flows}"
	rate="default"
fi
echo "Rate of transfer: ${rate}"
echo "Number of parallel flows: ${n_parallel_flows}"
echo "Report Interval (secs): ${report_interval_secs}"
echo "Protocol: ${proto}"
echo "MTU: ${mtu}"
echo "Duration (mins): ${duration_mins}"
while [ $i -lt ${duration_mins} ]; do
	iperf3 -c ${dst_ip} -V ${parallel_opt} -t ${report_interval_secs} -i ${interval_secs} ${proto_opt} ${rate_opt} ${mtu_opt} >> ${iperf_out} 2>&1
	if [ "${rate}" != "default" ]; then
		if [ ${proto} = "udp" ]; then
			val="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | grep -v datagrams | tail -1 | awk '{print $7}'`"
			unit="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | grep -v datagrams | tail -1 | awk '{print $8}'`"
		else
			val="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | tail -2 | awk '{print $7}'`"
			unit="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | tail -1 | awk '{print $8}'`"
		fi
	else
		if [ ${proto} = "udp" ]; then
			val="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | grep -v datagrams | tail -1 | awk '{print $6}'`"
			unit="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | grep -v datagrams | tail -1 | awk '{print $7}'`"
		else
			val="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | tail -2 | awk '{print $6}'`"
			unit="`grep -e "\[.*\]" ${iperf_out} | grep -v ID | tail -1 | awk '{print $7}'`"
		fi
	fi
	sum=0
	n_vals=0
	for v in $val; do
		n_vals=`expr $n_vals + 1`
		sum=`echo - | awk -v v1=${sum} -v v2=${v} '{print v1 + v2}'`
	done
	tp=`echo - | awk -v v1=${sum} -v v2=${n_vals} '{print v1 / v2}'`
	i=`expr $i + 1`
	echo "iperf iteration #$i completed with throughput $tp $unit"
done
