#!/bin/bash

usage() {
	echo "usage: ${progname} <path> [host]"
	exit 1
}
progname=`basename $0`
path=$1
hostname=$2

if [ -z "${path}" ]; then
	usage
fi
image=/var/tmp/`basename ${path}`

live_upgrade_path=/run/initramfs/live/upgrade
mkdir -p ${live_upgrade_path}
cd ${live_upgrade_path}
if [ -n "${hostname}" ]; then
	host=${hostname}
	scp root@${host}:${path} ${image}
fi
tar xf ${image}
./upgrimg.sh
