#!/bin/bash

progname=`basename $0`
if [ -z "$1" ]
then
	echo "usage: ${progname} <sandbox>"
	exit
fi
sbname=$1
export sbhead=~/Linux/src/sandbox/$sbname
if [ ! -d ${sbhead} ]
then
	echo "${progname}: bad sandbox name specified"
	echo "usage: ${progname} <sandbox>"
	exit
fi
export SANDBOX=${sbname}
echo "SANDBOX:" ${SANDBOX}
echo "sbhead:" ${sbhead}

TMPFILE=$(mktemp)
echo "source ~/.bashrc" > $TMPFILE
echo "cd ${sbhead}" >> $TMPFILE
echo "rm -f $TMPFILE" >> $TMPFILE
bash --rcfile $TMPFILE
