#!/bin/bash

progname=`basename $0`
if [ -z "$1" ]
then
	echo "usage: ${progname} <sandbox>"
	exit
fi
sbname=$1
export sbhead=~/Linux/src/sandbox/$sbname
if [ ! -d ${sbhead} ]
then
	echo "${progname}: bad sandbox name specified"
	echo "usage: ${progname} <sandbox>"
	exit
fi
export SANDBOX=${sbname}
bash
